import assets from '../../assets';

export const categoryIcon = {
  building: assets.icon_watch_building,
  politics: assets.icon_watch_politics,
  home: assets.icon_watch_home,
  law: assets.icon_watch_law,
  shield: assets.icon_watch_shield,
  crain: assets.icon_watch_crain,
  factory: assets.icon_watch_factory,
  drum: assets.icon_watch_drum,
  electronic: assets.icon_watch_electronic,
  eco: assets.icon_watch_eco,
  conductor: assets.icon_watch_conductor,
  it: assets.icon_watch_it,
  gps: assets.icon_watch_gps,
  airplane: assets.icon_watch_airplane,
  car: assets.icon_watch_car,
  heart: assets.icon_watch_heart,
  dna: assets.icon_watch_dna,
  lab: assets.icon_watch_lab,
  cell: assets.icon_watch_cell,
  rice: assets.icon_watch_rice,
  food: assets.icon_watch_food,
  dish: assets.icon_watch_dish,
  cart: assets.icon_watch_cart,
  bag: assets.icon_watch_bag,
  movie: assets.icon_watch_movie,
  house: assets.icon_watch_house,
  bed: assets.icon_watch_bed,
  health: assets.icon_watch_health,
  broad: assets.icon_watch_broad,
  customer: assets.icon_watch_customer,
};
export const categoryIcons = [
  { icon: assets.icon_watch_building, name: 'building' },
  { icon: assets.icon_watch_politics, name: 'politics' },
  { icon: assets.icon_watch_home, name: 'home' },
  { icon: assets.icon_watch_law, name: 'law' },
  { icon: assets.icon_watch_shield, name: 'shield' },
  { icon: assets.icon_watch_crain, name: 'crain' },
  { icon: assets.icon_watch_factory, name: 'factory' },
  { icon: assets.icon_watch_drum, name: 'drum' },
  { icon: assets.icon_watch_electronic, name: 'electronic' },
  { icon: assets.icon_watch_eco, name: 'eco' },
  { icon: assets.icon_watch_conductor, name: 'conductor' },
  { icon: assets.icon_watch_it, name: 'it' },
  { icon: assets.icon_watch_gps, name: 'gps' },
  { icon: assets.icon_watch_airplane, name: 'airplane' },
  { icon: assets.icon_watch_car, name: 'car' },
  { icon: assets.icon_watch_heart, name: 'heart' },
  { icon: assets.icon_watch_dna, name: 'dna' },
  { icon: assets.icon_watch_lab, name: 'lab' },
  { icon: assets.icon_watch_cell, name: 'cell' },
  { icon: assets.icon_watch_rice, name: 'rice' },
  { icon: assets.icon_watch_food, name: 'food' },
  { icon: assets.icon_watch_dish, name: 'dish' },
  { icon: assets.icon_watch_cart, name: 'cart' },
  { icon: assets.icon_watch_bag, name: 'bag' },
  { icon: assets.icon_watch_movie, name: 'movie' },
  { icon: assets.icon_watch_house, name: 'house' },
  { icon: assets.icon_watch_bed, name: 'bed' },
  { icon: assets.icon_watch_health, name: 'health' },
  { icon: assets.icon_watch_broad, name: 'broad' },
  { icon: assets.icon_watch_customer, name: 'customer' },
];

export const categoryColors = [
  [
    '#fd7061',
    '#ffaa5a',
    '#f1c209',
    '#d6c161',
    '#c7d435',
    '#87f571',
    '#84d27a',
    '#3ddb9a',
  ],
  [
    '#20bfa3',
    '#28a5bb',
    '#6cd7e4',
    '#5965d8',
    '#8176ee',
    '#4c5a81',
    '#949494',
    '#000000',
  ],
];
